name: update
on: 
  schedule:
    - cron: 30 14 12 2 *

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: delete original index
        run: rm -f index.html
      - name: delete original script
        run: rm -f javascripts/script.js
      - name: rename updated index
        run: mv updateindex.html index.html
      - name: rename updated script
        run: mv javascripts/updatescript.js javascripts/script.js
        
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "xman2156@gmail.com"
          git config --local user.name "xman2156"
          git add .
          git commit -m "Update for new epsiode"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
